### ISSUE TITLE
野指针的跟Zombie很不一样，判断条件应该有比较大的区别

### ISSUE THREAD

**Issue by lilidan** [summer20140803/TDFScreenDebugger#2]
https://github.com/lilidan/NSZombie  我提取出来的实现，跟NSZombie保持一致。

**Comment by summer20140803** [comment]
看了你的实现，应该是通过isa转换成Xcode zombie默认生成的类从而达到产生exception的效果，我这边是自定义的类修改isa指向，可能就内存字节对齐问题有一些区别吧？🧐

**Comment by lilidan** [comment]
你dealloc的时候没有调用destruct_instance()，有些对象就会出问题，比如weak的

**Comment by summer20140803** [comment]
感谢提醒，我回头试一下哈~
